repos:
-   repo: local
    hooks:
    -   id: clang-format-17
        name: clang-format-17
        description: Format C++        
        entry: clang-format-17 -i
        language: system
        files: \.(c|cpp|h|hpp|cc|hh)$
    -   id: spotless-formatter
        name: spotless-formatter
        description: Format Java
        entry: ./studio/gradlew -p studio spotlessApply
        language: system
        pass_filenames: false
        files: \.(java)$
    -   id: prettier-formatter
        name: prettier-formatter
        description: Format TypeScript/HTML/CSS
        entry: bash -c 'cd web && npm run format'
        language: system
        pass_filenames: false
        files: ^web/
    -   id: eslint-linter
        name: eslint-linter
        description: Lint and fix TypeScript
        entry: bash -c 'cd web && npm run lint:fix'
        language: system
        pass_filenames: false
        files: ^web/src/.*\.ts$
