name: Build & Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-artifacts.yml
    with:
      run-cpp-tests: true
      cpp-format-check: true
